### ISSUE TITLE
Possibly add brief description on the README

### ISSUE THREAD

**Issue by bbarker** [Terasology/QuestExamples#3]
Is the idea that these would be added as a module? (Sorry, I'm totally new to Terasology, though I've looked at it a few years ago and happy to see it is so active now. I'd love to play around with making a quest overlay/game on top of Tersaology.)

**Comment by bbarker** [comment]
I see the modules.txt now ... i guess it is, sorry!

**Comment by Cervator** [comment]
Just catching up with GitHub notifications - although this is already closed I couldn't resist throwing in a "YAY!" for any sort of attention the quest system could get :D

This is a classic example of us having a bunch of support for neat stuff that could even back an MMO-style questing system, just nobody has really put it to work anywhere yet. So I'd love to see some progress :)
