### ISSUE TITLE
Quest automatically fails 

### ISSUE THREAD

**Issue by e-aakash** [Terasology/QuestExamples#7]
Completed quests are shown with a green tick mark, but some time after the quest completion the mark changes to cross, signifying failed quest. 
How to reproduce:
1. Activate and complete a quest
2. Wait for some time
Quest will automatically be shown failed

**Comment by jdrueckert** [comment]
From what I've seen in the repo contents, this is not an issue of this tutorial repo but of the underlying `Tasks` repo.
That's why, this issue will be tracked there now instead of here: https://github.com/Terasology/Tasks/issues/30
